# Generated by Django 6.0.5 on 2026-06-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_catalogo_global_fase2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='produto',
            new_name='produtos_pr_is_acti_f29351_idx',
            old_name='produtos_pr_is_active_b7c8d9_idx',
        ),
        migrations.RenameIndex(
            model_name='produtoparametrosempresa',
            new_name='produtos_pr_empresa_854e50_idx',
            old_name='produtos_pr_empresa_2a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='produtoparametrosempresa',
            new_name='produtos_pr_produto_f836ef_idx',
            old_name='produtos_pr_produto__3d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='produto',
            name='classe_risco',
            field=models.CharField(choices=[('OUTRA', 'Não Aplicável')], default='OUTRA', help_text='Classificação de risco do produto (quando aplicável)', max_length=10, verbose_name='Classe de Risco'),
        ),
    ]
