# Generated by Django 6.0.5 on 2026-06-16 19:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_codigo_ibge_municipio'),
        ('fiscal', '0009_rename_fiscal_alert_loja_id_7a8f3a_idx_fiscal_aler_loja_id_423327_idx_and_more'),
        ('produtos', '0012_normalizar_classe_risco'),
        ('vendas', '0006_increase_document_fields_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='codigo_cnae',
            field=models.CharField(blank=True, max_length=7, verbose_name='CNAE Principal'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='csc_id',
            field=models.CharField(blank=True, max_length=6, verbose_name='CSC ID (NFC-e)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='csc_token',
            field=models.CharField(blank=True, max_length=36, verbose_name='CSC Token (NFC-e)'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='proximo_numero_rps',
            field=models.IntegerField(default=1, verbose_name='Próximo Número RPS'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalloja',
            name='serie_rps',
            field=models.CharField(default='RPS', max_length=5, verbose_name='Série RPS'),
        ),
        migrations.CreateModel(
            name='NotaFiscalConsumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('serie', models.CharField(default='001', max_length=3, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, verbose_name='Chave de Acesso')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('ambiente', models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=20, verbose_name='Ambiente')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online / E-commerce'), ('DELIVERY', 'Delivery')], default='PRESENCIAL', max_length=20, verbose_name='Modalidade')),
                ('cpf_consumidor', models.CharField(blank=True, max_length=14, verbose_name='CPF do Consumidor')),
                ('nome_consumidor', models.CharField(blank=True, max_length=60, verbose_name='Nome do Consumidor')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor dos Produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor ICMS')),
                ('forma_pagamento', models.CharField(default='01', help_text='01=Dinheiro, 03=Cartão, etc.', max_length=20, verbose_name='Forma de Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Pago')),
                ('valor_troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Troco')),
                ('xml_enviado', models.TextField(blank=True, verbose_name='XML Enviado')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML Retorno')),
                ('protocolo', models.CharField(blank=True, max_length=50, verbose_name='Protocolo')),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Autorização')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_consumidor', to='core.loja', verbose_name='Loja')),
                ('pedido_venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfce', to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'NFC-e',
                'verbose_name_plural': 'NFC-e',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscalConsumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.CharField(max_length=120)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cfop', models.CharField(default='5102', max_length=4)),
                ('ncm', models.CharField(blank=True, max_length=8)),
                ('cst_icms', models.CharField(default='400', max_length=3)),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nfce', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscalconsumidor', verbose_name='NFC-e')),
            ],
            options={
                'verbose_name': 'Item NFC-e',
                'verbose_name_plural': 'Itens NFC-e',
                'ordering': ['nota', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('numero_rps', models.IntegerField(verbose_name='Número RPS')),
                ('serie_rps', models.CharField(default='RPS', max_length=5, verbose_name='Série RPS')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('cpf_cnpj_tomador', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ Tomador')),
                ('nome_tomador', models.CharField(max_length=115, verbose_name='Nome Tomador')),
                ('email_tomador', models.CharField(blank=True, max_length=80, verbose_name='E-mail Tomador')),
                ('municipio_tomador', models.CharField(blank=True, max_length=7, verbose_name='Município Tomador (IBGE)')),
                ('codigo_servico', models.CharField(max_length=5, verbose_name='Código LC 116/2003')),
                ('discriminacao', models.TextField(verbose_name='Descrição do Serviço')),
                ('municipio_prestacao', models.CharField(max_length=7, verbose_name='Município de Prestação (IBGE)')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_deducoes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Deduções')),
                ('valor_iss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor ISS')),
                ('aliquota_iss', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5, verbose_name='Alíquota ISS')),
                ('iss_retido', models.BooleanField(default=False, verbose_name='ISS Retido')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Líquido')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=9, verbose_name='Código Verificação')),
                ('link_nfse', models.URLField(blank=True, verbose_name='Link NFS-e')),
                ('xml_enviado', models.TextField(blank=True, verbose_name='XML/Payload Enviado')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML/JSON Retorno')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_servico', to='core.loja', verbose_name='Loja')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse', to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'NFS-e',
                'verbose_name_plural': 'NFS-e',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notafiscalconsumidor',
            index=models.Index(fields=['loja', 'status'], name='fiscal_nota_loja_id_ad9c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalconsumidor',
            index=models.Index(fields=['chave_acesso'], name='fiscal_nota_chave_a_dc9e2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalconsumidor',
            unique_together={('loja', 'serie', 'numero')},
        ),
        migrations.AddIndex(
            model_name='notafiscalservico',
            index=models.Index(fields=['loja', 'status'], name='fiscal_nota_loja_id_334495_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalservico',
            unique_together={('loja', 'serie_rps', 'numero_rps')},
        ),
    ]
