# Generated by Django 6.0.5 on 2026-06-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_increase_document_fields_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='compradorpirotecnia',
            name='pdv_comprad_cpf_b8cc78_idx',
        ),
        migrations.RemoveIndex(
            model_name='compradorpirotecnia',
            name='pdv_comprad_data_na_7d65af_idx',
        ),
        migrations.RemoveIndex(
            model_name='compradorpirotecnia',
            name='pdv_comprad_created_3a0602_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrovendapirotecnia',
            name='pdv_registr_pedido__80c51a_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrovendapirotecnia',
            name='pdv_registr_comprad_ba85f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrovendapirotecnia',
            name='pdv_registr_produto_a15baf_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrovendapirotecnia',
            name='pdv_registr_created_d2b53e_idx',
        ),
        migrations.RemoveField(
            model_name='registrovendapirotecnia',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='registrovendapirotecnia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='registrovendapirotecnia',
            name='item_pedido',
        ),
        migrations.RemoveField(
            model_name='registrovendapirotecnia',
            name='pedido_venda',
        ),
        migrations.RemoveField(
            model_name='registrovendapirotecnia',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='registrovendapirotecnia',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CompradorPirotecnia',
        ),
        migrations.DeleteModel(
            name='RegistroVendaPirotecnia',
        ),
    ]
